---
openapi: 3.0.0
paths:
  "/user":
    get:
      operationId: UserController_findUsers
      parameters: []
      responses:
        '200':
          description: Successful operation
      tags:
      - User
    post:
      operationId: UserController_createUser
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateUserDto"
      responses:
        '201':
          description: User created
        '400':
          description: Bad request. Missing required properties in the body
      tags:
      - User
  "/user/{id}":
    get:
      operationId: UserController_findUser
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: User not found
      tags:
      - User
    put:
      operationId: UserController_updateUserPassword
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateUserPasswordDto"
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request. id is not valid UUID or missing required properties
            in the body
        '404':
          description: User not found
      tags:
      - User
    delete:
      operationId: UserController_removeUser
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '204':
          description: User deleted
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: User not found
      tags:
      - User
  "/artist":
    get:
      operationId: ArtistController_findAll
      parameters: []
      responses:
        '200':
          description: Successful operation
      tags:
      - Artist
    post:
      operationId: ArtistController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ArtistDto"
      responses:
        '201':
          description: Artist created
        '400':
          description: Bad request. Missing required properties in the body
      tags:
      - Artist
  "/artist/{id}":
    get:
      operationId: ArtistController_findOne
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: Artist not found
      tags:
      - Artist
    put:
      operationId: ArtistController_update
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ArtistDto"
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request. id is not valid UUID or missing required properties
            in the body
        '404':
          description: Artist not found
      tags:
      - Artist
    delete:
      operationId: ArtistController_remove
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '204':
          description: Artist deleted
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: Artist not found
      tags:
      - Artist
  "/album":
    get:
      operationId: AlbumController_findAll
      parameters: []
      responses:
        '200':
          description: Successful operation
      tags:
      - Album
    post:
      operationId: AlbumController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AlbumDto"
      responses:
        '201':
          description: Album created
        '400':
          description: Bad request. Missing required properties in the body
      tags:
      - Album
  "/album/{id}":
    get:
      operationId: AlbumController_findOne
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: Album not found
      tags:
      - Album
    put:
      operationId: AlbumController_update
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AlbumDto"
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request. id is not valid UUID or missing required properties
            in the body
        '404':
          description: Album not found
      tags:
      - Album
    delete:
      operationId: AlbumController_remove
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '204':
          description: Album deleted
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: Album not found
      tags:
      - Album
  "/track":
    get:
      operationId: TrackController_findAll
      parameters: []
      responses:
        '200':
          description: Successful operation
      tags:
      - Track
    post:
      operationId: TrackController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TrackDto"
      responses:
        '201':
          description: Track created
        '400':
          description: Bad request. Missing required properties in the body
      tags:
      - Track
  "/track/{id}":
    get:
      operationId: TrackController_findOne
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: Track not found
      tags:
      - Track
    put:
      operationId: TrackController_update
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TrackDto"
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request. id is not valid UUID or missing required properties
            in the body
        '404':
          description: Track not found
      tags:
      - Track
    delete:
      operationId: TrackController_remove
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '204':
          description: Track deleted
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: Track not found
      tags:
      - Track
  "/favs":
    get:
      operationId: FavsController_findAll
      parameters: []
      responses:
        '200':
          description: Successful operation
      tags:
      - Favorites
  "/favs/track/{id}":
    post:
      operationId: FavsController_saveFavTrack
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '201':
          description: Track added to favorites
        '400':
          description: Bad request. id is not valid UUID
        '422':
          description: Cannot add non-existing track favorites
      tags:
      - Favorites
    delete:
      operationId: FavsController_removeFavTrack
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '204':
          description: Track deleted
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: Favorite track not found
      tags:
      - Favorites
  "/favs/album/{id}":
    post:
      operationId: FavsController_saveFavAlbum
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '201':
          description: Album added to favorites
        '400':
          description: Bad request. id is not valid UUID
        '422':
          description: Cannot add non-existing album favorites
      tags:
      - Favorites
    delete:
      operationId: FavsController_removeFavAlbum
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '204':
          description: Album deleted
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: Favorite album not found
      tags:
      - Favorites
  "/favs/artist/{id}":
    post:
      operationId: FavsController_saveFavArtist
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '201':
          description: Artist added to favorites
        '400':
          description: Bad request. id is not valid UUID
        '422':
          description: Cannot add non-existing artist favorites
      tags:
      - Favorites
    delete:
      operationId: FavsController_removeFavArtist
      parameters:
      - name: id
        required: true
        in: path
        schema:
          format: uuid
          type: string
      responses:
        '204':
          description: Artist deleted
        '400':
          description: Bad request. id is not valid UUID
        '404':
          description: Favorite artist not found
      tags:
      - Favorites
info:
  title: Home Library Service
  description: Home music library service
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    CreateUserDto:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
      required:
      - login
      - password
    UpdateUserPasswordDto:
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
      required:
      - oldPassword
      - newPassword
    ArtistDto:
      type: object
      properties:
        name:
          type: string
        grammy:
          type: boolean
      required:
      - name
      - grammy
    AlbumDto:
      type: object
      properties:
        name:
          type: string
        year:
          type: number
        artistId:
          type: string
          nullable: true
          format: uuid
      required:
      - name
      - year
      - artistId
    TrackDto:
      type: object
      properties:
        name:
          type: string
        artistId:
          type: string
          nullable: true
          format: uuid
        albumId:
          type: string
          nullable: true
          format: uuid
        duration:
          type: number
      required:
      - name
      - artistId
      - albumId
      - duration